# Build stage
FROM quay.io/quarkus/quarkus-micro-image:2.0 AS build
WORKDIR /build
COPY --chown=quarkus:quarkus . .
USER quarkus
RUN ./mvnw package -DskipTests

# Runtime stage
FROM quay.io/quarkus/quarkus-micro-image:2.0
WORKDIR /deployments
COPY --chown=quarkus:quarkus /build/target/quarkus-app/lib/ /deployments/lib/
COPY --chown=quarkus:quarkus /build/target/quarkus-app/*.jar /deployments/
COPY --chown=quarkus:quarkus /build/target/quarkus-app/app/ /deployments/app/
COPY --chown=quarkus:quarkus /build/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER quarkus
CMD ["/deployments/quarkus-run.jar"]